### ISSUE TITLE
网页的临时情景模式在浏览器关闭的情况下不会重置

### ISSUE THREAD

**Issue by AmenLi** [zero-peak/ZeroOmega#10]
### SwitchyOmega version / SwitchyOmega 版本
3.2.2

### Browser version & OS version / 浏览器名称、版本及操作系统版本
版本 126.0.6478.115（正式版本） （64 位）
Windows 11 23h2 6月更新

### Problem description / 问题描述
网页的临时情景模式在浏览器关闭的情况下不会重置
“关闭 Google Chrome 后继续运行后台应用” 已关闭

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)
![PixPin_2024-06-20_00-30-59](https://github.com/suziwen/ZeroOmega/assets/5909257/3674fff9-5169-4396-a1e0-9607e52ccafb)

一个网址临时随便选择一种情景模式。和扩展的当前模式不一样也行。
关闭浏览器后，临时的选择，无法被重置成扩展的当前模式

#### Expected behavior / 期望发生的情况
关闭浏览器后，临时的情景模式，重置成扩展的当前模式

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）
无法被重置

**Comment by suziwen** [comment]
能录个视频，看下你的操作步骤吗？
