### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by PeachJamCrew** [zero-peak/ZeroOmega#18]
Hello.
Please, add android support to Firefox extension. 
I have tried to install it manually, but after install extension only show this screen and do nothing. Clicking on every option in the list redirect you to empty page 
![Screenshot_2024-08-09-09-32-09-62_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/d646b75a-0990-4ec6-8bd1-4135ade7513d)
![Screenshot_2024-08-09-09-37-03-30_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/57029909-00bc-4ba6-a791-d2b25a850884)
![Screenshot_2024-08-09-09-39-05-20_3aea4af51f236e4932235fdada7d1643](https://github.com/user-attachments/assets/306ae67a-eb97-4c50-a99e-8de98d2a288c)

**Comment by suziwen** [comment]
ZeroOmega support **Firefox for Android** is now available. You can search ZeroOmega on [AMO](https://addons.mozilla.org/en-US/firefox/addon/zeroomega/), or directly download [3.3.9](https://github.com/suziwen/ZeroOmega/releases/tag/3.3.9) .
