### ISSUE TITLE
Stop working if "Never remember history" enabled in Firefox

### ISSUE THREAD

**Issue by dyhkwong** [zero-peak/ZeroOmega#21]
### ZeroOmega version

3.3.5

### Browser version & OS version

Firefox 129.0, this issue is not OS-specific

#### Steps to reproduce issue

1. Install ZeroOmega
2. Go to "Settings" - "Privacy & Security" - "History" - "Firefox will" - Select "Never remember history"
3. Any changes made in ZeroOmega settings can't take effect.

#### Expected behavior

Changes made in ZeroOmega settings can take effect.

#### Actual behavior

Data of ZeroOmega can't persist if "Never remember history" enabled in Firefox.

**Comment by suziwen** [comment]
ZeroOmega is developed using the mv3 specification, and mv3 must be run under service worker. However, firefox is not fully compatible with service worker in private mode, so there is no good solution for now. Either try to use switchyomega or wait for firefox to be compatible in the future.

[Service workers not compatible](https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/index.html#service-workers-not-compatible)

The most fundamental reason may be: **Firefox in "never remember history" mode will disable IndexedDB**

**Comment by suziwen** [comment]
I converted indexeddb to localStorage, the latest 3.3.6 may work.

https://github.com/suziwen/ZeroOmega/releases/tag/3.3.6
