### ISSUE TITLE
Allow large profiles to be synchronized

### ISSUE THREAD

**Issue by Michael1297** [zero-peak/ZeroOmega#26]
Related to https://github.com/FelisCatus/SwitchyOmega/issues/1867 https://github.com/FelisCatus/SwitchyOmega/issues/333#issuecomment-152404221
Now that the extension supports syncing to GitHub gist you can remove the storage space limitation.
![image](https://github.com/user-attachments/assets/ad1680af-ca01-4340-8ef1-36f1da1b8d26)

**Comment by zero-top** [comment]
Although some of the quota exceed error related logic is still retained in the code (because the old code logic is scattered, some places may not be deleted cleanly). However, I have deleted the most important related code, so the new gist sync should not pop up this error like before.

**Comment by zero-top** [comment]
It should be that the old configuration file has disabled synchronization. The new Gist is not adapted it.

If it is a new configuration file, the added rules are not subject to the file size limit.

https://github.com/zero-peak/ZeroOmega/issues/25#issuecomment-2315142133

**Comment by zero-top** [comment]
3.3.11 fixed

**Comment by Michael1297** [comment]
Thanks!
