### ISSUE TITLE
Add an option to change the profile for all switch rules

### ISSUE THREAD

**Issue by Michael1297** [zero-peak/ZeroOmega#29]
Hello.
Please add this option. Now I do it in Notepad++ 😀

**Comment by zero-top** [comment]
I don't quite understand your idea or workflow, could you explain it in more detail?

**Comment by Michael1297** [comment]
![Снимок экрана 2024-08-28 151239](https://github.com/user-attachments/assets/d102f295-2cc3-4caf-bb26-776390220fa5)
When you click on the button, a list of all profiles appears. When you click on the selected profile, it is applied to all rules.

**Comment by zero-top** [comment]
This is similar to the **Virtual Profile** function. You can learn more about the usage of **Virtual Profile** yourself.

![image](https://github.com/user-attachments/assets/bbbc78a3-4363-4d1e-96d7-48d7ae48c68c)

**Comment by Michael1297** [comment]
I didn't know about this, thank you.
