### ISSUE TITLE
3.3.12 版本firefox安卓无法使用

### ISSUE THREAD

**Issue by Yxue-1906** [zero-peak/ZeroOmega#42]
### Browser version & OS version / 浏览器名称、版本及操作系统版本
Firefox安卓稳定版与nightly

### Problem description / 问题描述
似乎无法正常加载扩展

![Screenshot_2024-09-16-01-21-17-28_984e1414ae90666a90f12ff17ec14a7f](https://github.com/user-attachments/assets/7bc26101-d935-4bce-ae2f-ed47e55736af)
![Screenshot_2024-09-16-01-22-41-49_984e1414ae90666a90f12ff17ec14a7f](https://github.com/user-attachments/assets/1bc515ea-0aee-409a-a2a9-104735c2713f)

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1.
2.
3.

**Comment by zero-top** [comment]
更新下 `3.3.13`

**Comment by Yxue-1906** [comment]
可以使用了 感谢
