### ISSUE TITLE
3.3.12版本PC端Chrome显示此插件发生了错误，修复按钮无法点击

### ISSUE THREAD

**Issue by iamspark1e** [zero-peak/ZeroOmega#43]
#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

版本号：版本 128.0.6613.138（正式版本） （64 位）

1. 应该是Chrome自动升级到了3.3.12，显示此插件发生了错误，修复按钮无法点击；
2. 下载了3.3.13的xpi包，解压后使用加载已解压的扩展程序，不再显示修复按钮；（由于没有提供crx包仅仅做了一下尝试）点击扩展程序的管理界面，Console报错：Possibly unhandled rejection: {"message":"Could not establish connection. Receiving end does not exist."} undefined angular.min.js:129
3. 回退到3.3.11版本，下载crx文件加载，移除当前错误版本，加载已解压的扩展程序，加载旧的bak文件，恢复。

#### Expected behavior / 期望发生的情况

3.3.12不应被chrome提示需要修复

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）

显示此插件发生了错误，修复按钮无法点击

**Comment by iamspark1e** [comment]
补充：刚刚发现旧版的3.3.12还在，由于我解压的3.3.11现在能够正常工作，弹出了chrome的修复弹窗，点击修复，3.3.12版本插件的所有配置项丢失，但是看起来可用……

**Comment by zero-top** [comment]
测试了下从 chrome store 安装 3.3.12, 没有出现你说的情况，可能是你当时从 chrome store 更新下载时，网络出错，造成下载的包不完整引起的．你再试下从 chrome store 安装呢？

------

3.3.13 只涉及 firefox 更新，所以就没有提供 chrome 版本， release 主版本还是 3.3.12  的.

**Comment by iamspark1e** [comment]
目前重新从Store安装并且使用旧的bak文件恢复没有再次出现需要修复，暂时也未观察到其他报错，怀疑确实是当时网络波动造成了安装包不完整，暂时先close，如果后续复现我再追加相关信息
