### ISSUE TITLE
Google Lens in chrome does not use Proxy

### ISSUE THREAD

**Issue by eastLaugh** [zero-peak/ZeroOmega#45]
ZeroOmega 3.3.12
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

**Comment by zero-top** [comment]
This is the same as Google's built-in translation.

 Chrome handles these network requests separately, and all the proxy extension currently known cannot add proxies to these requests.
