### ISSUE TITLE
Add the function of exporting rules as a pac file

### ISSUE THREAD

**Issue by goddade** [zero-peak/ZeroOmega#47]
### Problem description / 问题描述

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1.
2.
3.

**Comment by zero-top** [comment]
![image](https://github.com/user-attachments/assets/35e1a1a7-a7fb-4f45-8020-55fa4c0c49b5)

**Comment by goddade** [comment]
Thank you
