### ISSUE TITLE
Add subdomains auto support for conditions

### ISSUE THREAD

**Issue by Verity-Freedom** [zero-peak/ZeroOmega#50]
![image](https://github.com/user-attachments/assets/6a14c9a5-ebbc-4b0d-905e-d40a3159e2a1)

Here I'm on chromewebstore.google.com, but on Condition Details it is written that I'm on google.com, which is not really true, because google.com is a domain, while chromewebstore.google.com is a subdomain. I can add the condition for chromewebstore.google.com only by manually typing it. Here, for example, how it is implemented in Runet censorship bypass extension, which I used before Switchy/Zero Omega:

![image](https://github.com/user-attachments/assets/8cdd6cc3-3f21-4b52-a002-6af39a28f281)

They are using the subdomain automatically. In ideal, I want the exact same behavior from ZeroOmega when we are talking about conditions.

**Comment by zero-top** [comment]
`3.3.16`

![image](https://github.com/user-attachments/assets/57dcc771-e6cb-47be-990d-a5b477f2ab29)

**Comment by Verity-Freedom** [comment]
@zero-top that's great, thank you, I really like it! It's really better than the old switchy now.

For the next version I want it probably to show all proxified domains instead of only failed ones ([1](https://github.com/zero-peak/ZeroOmega/issues/49)), but these changes are already so great, my respect! I will migrate from switchy to zero now.

**Comment by Verity-Freedom** [comment]
You made me really happy ^^
