### ISSUE TITLE
Keep asking to re-enter username/password with HTTP proxies

### ISSUE THREAD

**Issue by kvalter** [zero-peak/ZeroOmega#52]
I have some HTTP proxies and auto switch rules configured, for example amazon.com uses a USA proxy. The username and password is configured in SwitchyOmega settings, but sometimes Chrome still shows a popup asking me to re-enter the credentials. Then it tends to remember it for a while but then starts to ask me for it again later. This is not right after restarting Chrome either, it's been running for a while when it happens. Even if I set global proxy explicitly it still asks for credentials, only solution is entering them or disabling proxy by setting it to direct (but then re-enabling proxy still asks for credentials).
Screenshot: [https://disk.yandex.ru/i/e0504pkiYQI3mQ](https://disk.yandex.ru/i/e0504pkiYQI3mQ)

This is not necessarily specific to HTTP, I haven't tested with other types.

### ZeroOmega version / ZeroOmega 版本
Version 3.3.14

### Browser version & OS version / 浏览器名称、版本及操作系统版本

Google Chrome Version 129.0.6668.90 (Official Build) (64-bit)

**Comment by SoutouKakka** [comment]
Experiencing the same issue.  
I have multiple HTTP proxy configured. Everytime I enter the credentials in the prompt, it forgets all other credentials I entered for the other proxies.

**ZeroOmega version**
3.3.14

**Browser version**
版本 130.0.6723.59 (正式版本) (64 位元)

**Comment by interu** [comment]
Even though my ID/Password is stored in the Proxy Authentication settings, that information is not given when making a request to the Proxy server.
Proxy-Authorization header should be added to the request, but Chrome on MacOS does not seem to add it.
Therefore, response with HTTP status code 407 is returned.

It is necessary to wait until the ID/Password input Prompt is displayed, making it very difficult to use.

**OS**
MacOS Sequoia 15.0.1

**Z‍e‍r‍o‍Omega Version**
3.3.14

**Chrome**
130.0.6723.70（Official Build） （arm64)

**Comment by agg-one** [comment]
any solution?

**Comment by zero-top** [comment]
#5
