### ISSUE TITLE
[建议] 增加 WebDAV 自动同步功能

### ISSUE THREAD

**Issue by LegendAdmin** [zero-peak/ZeroOmega#53]
这样可以通过NAS同步多浏览器数据

ZeroOmega 3.3.14
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.95 Safari/537.36

**Comment by lhuanyun** [comment]
举手投一票,谢谢作者.现在都是手动webdav同步..

**Comment by zero-top** [comment]
#24 

这个暂时应该不会考虑，感觉 Gist 同步已经基本满足使用需求了．

不过也欢迎提交 Pull requests, 实现多种不同服务接口模式．

**Comment by chung1912** [comment]
同意webdav，比如直接坚果云同步

**Comment by foresee-io** [comment]
3.5.0版本已经支持了，欢迎体验。

WebDAV is supported at 3.5.0 release, you can use them in Microsoft Edge browser.
