### ISSUE TITLE
如何查看和清除临时规则

### ISSUE THREAD

**Issue by narouss** [zero-peak/ZeroOmega#54]
### ZeroOmega version / ZeroOmega 版本
Proxy SwitchyOmega 3 (ZeroOmega) 3.3.14

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Google Chrome 129.0.6668.90 
Windows 10 专业版 22H2 19045.4894

### Problem description / 问题描述

1.访问chatgpt添加了临时规则，想了解下添加的临时规则在哪里查看？如何清除临时规则？
![PixPin_2024-10-17_11-22-58](https://github.com/user-attachments/assets/b30906c9-5640-434f-ba13-19aa70c53e62)

**Comment by RunningFelix** [comment]
Reopen your browser and the temp condition will be cleared!

**Comment by zero-top** [comment]
https://github.com/zero-peak/ZeroOmega/issues/62#issuecomment-2525547347
