### ISSUE TITLE
Add system proxy as a default option in auto

### ISSUE THREAD

**Issue by Verity-Freedom** [zero-peak/ZeroOmega#61]
There is no system proxy option in default auto mode section, which means auto cant be used with other system proxy at the same time. Direct forces auto mode to not use any proxy. The preferable behavior is to proxy by omega only certain sites and to use system proxy for all others while being in auto mode.

P. S. I'm not entirely sure is it possible or not possible to do technically.
![image](https://github.com/user-attachments/assets/ee9279eb-cc23-44a4-8f0e-76215b72a7c7)
![image](https://github.com/user-attachments/assets/e7d4eefa-2ad7-4c97-9b67-745134ab07ce)

**Comment by AnyWAT** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/2421

**Comment by Verity-Freedom** [comment]
> [FelisCatus#2421](https://github.com/FelisCatus/SwitchyOmega/issues/2421)

@AnyWAT I don't understand chinese at all; I can't even translate chinese for it to be understandable enough.

**Comment by Verity-Freedom** [comment]
But as I see it was an issue before already, yes.

**Comment by AnyWAT** [comment]
https://geph.io/

**Comment by AnyWAT** [comment]
> but since there is only a direct mode in auto

不对，是直接连接 + 各个自建的代理服务器，如你的PSIPHON和TOR

>将系统代理的协议、端口设置为某情景模式（代理服务器），再添加与该代理服务器配套的AutoSwitch。。。

**Comment by AnyWAT** [comment]
任一自动切换可通过手动添加切换规则，使用任何正在运行的代理服务器，当然包括你的“系统代理”。

**Comment by Verity-Freedom** [comment]
@zero-top im not entirely sure is this one even possible or not so im closing it for now. The issue is there is no system profile for conditions in auto, but I don't know is it possible to add it. There is probably the reason it wasn't initially here in the first place.
![image](https://github.com/user-attachments/assets/a34ccba8-f9dc-461f-b495-ac429997b119)
