### ISSUE TITLE
【功能请求】一键清理临时条件

### ISSUE THREAD

**Issue by Mishasama** [zero-peak/ZeroOmega#62]
#54 
有时我们会通过这个功能来临时添加大量条件，但这些条件由于不是顶层网页，所以我们无法方便的通过菜单来逐一取消。
![image](https://github.com/user-attachments/assets/fe56ca61-7248-4380-9962-021a866c5cfd)
能否在添加按钮旁边增加一个一键清理所有临时条件的功能？这样就不用重启浏览器从而丢失页面的状态了。（比如一些已经填写了的表单等）

ZeroOmega 3.3.14
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0

**Comment by Mishasama** [comment]
话说该整理一下扩展里的文本内容了，批量把`Switchy`替换成`Zero`，避免新用户困惑。

**Comment by zero-top** [comment]
3.3.16 版本提供了一个重新加载的上下文菜单．右键点击图标后，选择 `Reload` 菜单项，就可以清空所有临时规则．

![image](https://github.com/user-attachments/assets/c7d38bf0-e0a4-43b7-847e-3bcfe7f73530)

**Comment by Mishasama** [comment]
确认功能有效。
