### ISSUE TITLE
Unable to create new proxy profile

### ISSUE THREAD

**Issue by SebGay** [zero-peak/ZeroOmega#64]
### ZeroOmega version / ZeroOmega 版本
3.3.15

### Browser version & OS version / 浏览器名称、版本及操作系统版本
132.0.2 (aarch64)
macOS 15.1.1 (24B91)

### Problem description / 问题描述
When trying to create a new proxy profile, the error "The name of the profile must not be empty." persists and blocks creation even when a name is entered. The same persists for the other possible types (Switch/PAC/Virtual)

![image](https://github.com/user-attachments/assets/793f00ff-4986-4ce9-8cb2-8bffe748613f)

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1. Open ZeroOmega options
2. Click 'New Profile"

#### Expected behavior / 期望发生的情况
After entering a name I am amble to proceed to create a new profile

**Comment by procodr** [comment]
Same here, it seems we have undefined references.
The console error on Firefox:
![image](https://github.com/user-attachments/assets/dce95470-a9bb-4925-89a1-580b5ef32ac3)

**Comment by suziwen** [comment]
Fixed in v3.3.16.

**Comment by SebGay** [comment]
Thank you everyone for the quick fix!

**Comment by procodr** [comment]
@zero-top For the release, please add required tag.
Thanks for the great work. 🚀

**Comment by zero-top** [comment]
https://github.com/zero-peak/ZeroOmega/releases/tag/3.3.16
