### ISSUE TITLE
自动切换模式，添加规则仍然不能正常加载

### ISSUE THREAD

**Issue by dh12306** [zero-peak/ZeroOmega#65]
zero 版本：版本 3.3.14
![QQ_1732780026311](https://github.com/user-attachments/assets/0a89aab6-967d-412a-af43-efd2c7083ff0)
chrome版本：
版本 131.0.6778.86（正式版本） （64 位）
系统：win10 
问题：
自动切换场景，在添加了规则之后，仍然显示资源未加载，并且多次在弹出窗口添加也未生效
网站是这个：https://gmgn.ai/meme/6kyeCbaf?chain=sol
![QQ_1732780242474](https://github.com/user-attachments/assets/42298f5f-e9d7-4460-9845-507b5c13ecdc)

添加的规则：
![QQ_1732780156160](https://github.com/user-attachments/assets/95ed681f-886c-40d5-b6c0-b2bdcb375a24)

页面还是显示未加载资源：
![QQ_1732780181468](https://github.com/user-attachments/assets/0696b5e2-ee12-4e7f-9ab3-c4e536d47ab0)

点击添加条件不生效：
![QQ_1732780313378](https://github.com/user-attachments/assets/a636fdef-7f39-4b6d-99c6-c9f66a92ce8c)

**Comment by AnyWAT** [comment]
> 自动切换场景，在添加了规则之后，仍然显示资源未加载，并且多次在弹出窗口添加也未生效

![image](https://github.com/user-attachments/assets/0ce3f331-b2cd-4e8d-bb3d-b153e94e701b)
其实就是你的代理不给力而已，与此插件无关。
![image](https://github.com/user-attachments/assets/d0c53cec-ef2e-4d50-876a-2f5d18224281)
瞧瞧你的“代理模式”设置截图？

**Comment by dh12306** [comment]
> > 自动切换场景，在添加了规则之后，仍然显示资源未加载，并且多次在弹出窗口添加也未生效
> 
> ![image](https://private-user-images.githubusercontent.com/37962734/390700000-0ce3f331-b2cd-4e8d-bb3d-b153e94e701b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjY5OTEsIm5iZiI6MTczMjg2NjY5MSwicGF0aCI6Ii8zNzk2MjczNC8zOTA3MDAwMDAtMGNlM2YzMzEtYjJjZC00ZThkLWJiM2QtYjE1M2U5NGU3MDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA3NTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlM2YwOWViNzQ5ZTU1Y2EwZjNkOWJlYWJhZTE4MWJhMGMxMmE4MDNlMmFhNzliZjY0YTk1M2MxNDhlNzgwY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pCLKYgIpldkPqudpjiybZiUZFeD1jlvJN6DFokFjnoA) 其实就是你的代理服务器不给力而已，与此插件无关。 ![image](https://private-user-images.githubusercontent.com/37962734/390700637-d0c53cec-ef2e-4d50-876a-2f5d18224281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjY5OTEsIm5iZiI6MTczMjg2NjY5MSwicGF0aCI6Ii8zNzk2MjczNC8zOTA3MDA2MzctZDBjNTNjZWMtZWYyZS00ZDUwLTg3NmEtMmY1ZDE4MjI0MjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA3NTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZmJmMTAwMDJjYzgwOWI0YjY4OGE1MjBiNTRlZWE4ZDExYzc5MGRhMzhlOWQxMjk5MDc4YTlhYWQ3ODM3ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PKBYsT0L5XrIDTVEImoxfc4t6WaBwB6crVhyZANExuE) 瞧瞧你的“代理模式”设置的截图？ 如果代理支持2个协议与端口，貌似设置齐全会更佳？如： ![image](https://private-user-images.githubusercontent.com/37962734/390702717-3c0937a0-4d34-441a-8c34-12b3a3537e9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4NjY5OTEsIm5iZiI6MTczMjg2NjY5MSwicGF0aCI6Ii8zNzk2MjczNC8zOTA3MDI3MTctM2MwOTM3YTAtNGQzNC00NDFhLThjMzQtMTJiM2EzNTM3ZTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA3NTEzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZDNiYThhMzdmOWFlOThhOWFjZmQwZTk2OGY1MzI0MTQ1ZDgyYzc1ZTIzNWI0MGRkY2U3YjQzMTcyZDA2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QVXDTkK1ZElLGJMdQXK5NUznufr6X-IJRSTVQgLtDpc)


**换了代理，增加了http接口，现在好了，感谢**

![QQ_1732867075602](https://github.com/user-attachments/assets/0bf541b8-bb97-4094-98d4-d28fbb512e30)
