### ISSUE TITLE
LInux下Chrome的此插件auto模式使用问题

### ISSUE THREAD

**Issue by Pkkkkkkkk** [zero-peak/ZeroOmega#66]
在linux下的chrome使用本插件时，选用auto模式无法正常使用代理，网络也无法使用，只能用直接代理或者系统代理。代理程序使用的是clash for window的linux版本

配置与window上一致，但是window端可以正常使用auto switch模式
原版Omega也是这样的情况
谢谢！

ZeroOmega 3.3.14
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36

**Comment by daic11** [comment]
Same problem, can't use auto switch in chrome on linux.
