### ISSUE TITLE
Refreshing the page in builtin profile bug

### ISSUE THREAD

**Issue by Verity-Freedom** [zero-peak/ZeroOmega#71]
![image](https://github.com/user-attachments/assets/49672229-9da8-407a-93ea-c77504eebdac)

This is refresh, I clicked it, and here it is.

**Comment by Verity-Freedom** [comment]
@zero-top I think its clear enough this is a bug.

**Comment by zero-top** [comment]
Thanks for your report.   It will be fixed in the next release.

**Comment by Verity-Freedom** [comment]
Can't wait to see the next version ;v;

**Comment by Verity-Freedom** [comment]
@zero-top how to support you? Maybe like Paypal donations. That is my second issue that was approved by you, I really like what you are doing, I wrote a guide for your extension in my little Tor Portable repo for Russian fellas. If you ever need money, just know, we will support you. Have a nice day.

**Comment by zero-top** [comment]
Just be patient, please. The review time of the Chrome Store has been a bit long recently.  

----------------

Thank you for your support. 

ZeroOemga currently has no plans to accept donations. We will continue to solve problems in ZeroOmega and improve it.

For now, the best way to support this project is to contribute or recommend it to others.

**Comment by zero-top** [comment]
https://github.com/zero-peak/ZeroOmega/releases/tag/3.3.17
